trigger:
  branches:
    include:
      - main  # specify the branch to trigger the pipeline

jobs:
  - job: DeployS3
    displayName: "Deploy S3 Bucket using Terraform"
    pool:
      name: "new-pool"  # Specify your self-hosted agent pool name here
    steps:
      - checkout: self  # Automatically checks out the repository code

      - task: UseTerraform@0
        inputs:
          command: 'init'
          workingDirectory: $(System.DefaultWorkingDirectory)
          additionalArgs: '-no-color'

      - task: UseTerraform@0
        inputs:
          command: 'apply'
          workingDirectory: $(System.DefaultWorkingDirectory)
          additionalArgs: '-auto-approve -no-color'
