trigger:
  branches:
    include:
      - main  # specify the branch to trigger the pipeline

jobs:
  - job: DeployS3
    displayName: "Deploy S3 Bucket using Terraform"
    pool:
      name: "new-pool"  # Specify your self-hosted agent pool name here
    steps:
      - checkout: self  # Automatically checks out the repository code

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            terraform init
            terraform apply -auto-approve
